# 私钥文件路径
key_filename: /home/ansible/.ssh/id_rsa.pub
# 项目包上传目录
upload_folder: /home/ansible
# 编译服务器地址
build_server: ansible@192.168.6.22:22
# 项目运行端口，tomcat配置
project_port: 9301
# tomcat配置文件中docbase目录项目名称，如/data/web/pi-sys目录中的pi-sys
project_name: risk-control
# 编译服务器上，源码存放目录
build_folder: /code/riskcontrol-alpha-beta/alpha/riskcontrol
# rsync服务器访问账号
rsync_user: rcuser
# rsync服务器地址
rsync_host: 192.168.6.22
# rsync服务器端口
rsync_port: 873
# rsync服务器section
rsync_section: riskcontrol-alpha
# 当前工具conf目录rsync密码文件名称，必须创建自定义文件，并修改权限0600，用户和属组为root:root
passwd_file: riskcontrol.passwd
# 存放同步项目编译后代码的目录，目录必须以/结尾，最后一个目录名称必须和project_name保持一致
local_storage: /rsync/riskcontrol/
# 压缩包名，名称必须和project_name保持一致，文件后缀为.zip，如project_name为pi-app，包名为：pi-app.zip
package_name: riskcontrol-0.0.1-SNAPSHOT.jar
# 项目备份目录，必须手动创建，目录不能以/结尾
backup_folder: /web/share/web_bak/riskcontrol
# 启动riskcontrol服务脚本
shell_name: start-rk.sh

